language: java
jdk: oraclejdk11
before_install:
  - chmod +x gradlew
  - chmod +x travisBuild.sh
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
install: travis_wait 30 ./travisBuild.sh
deploy:
  - provider: script
    script: ./gradlew bintrayUpload
    skip_cleanup: true
    on:
      tags: true